services:
  - type: web
    name: smartcli-web-api
    runtime: docker
    rootDir: smartcli-web-backend
    plan: free
    region: singapore
    healthCheckPath: /api/categories
    autoDeploy: true
    envVars:
      - key: SMARTCLI_WEB_ALLOWED_ORIGINS
        sync: false
